name: 'Setup Registry Authentication'
description: 'Configure registry settings and authenticate based on build type (Community or Prime)'

# Note the action set the following environment variables:
# - DOCKER_REGISTRY: The registry URL (e.g., docker.io for community builds, set from vault secrets for prime builds)
# - DOCKER_USERNAME: The username for registry authentication
# - DOCKER_PASSWORD: The password for registry authentication

inputs:
  prime_build:
    description: 'Indicates whether the build is a Prime build. Set to "true" for Prime builds, otherwise "false".'
    required: false

runs:
  using: "composite"
  steps:
    - name: Set Environment Variables
      shell: bash
      if: ${{ inputs.prime_build != 'true' }}
      run: |
        echo "DOCKER_REGISTRY=docker.io" >> $GITHUB_ENV

    - name: Read Secrets for Community Build
      uses: rancher-eio/read-vault-secrets@main
      if: ${{ inputs.prime_build != 'true' }}
      with:
        secrets: |
          secret/data/github/repo/${{ github.repository }}/dockerhub/rancher/credentials username | DOCKER_USERNAME ;
          secret/data/github/repo/${{ github.repository }}/dockerhub/rancher/credentials password | DOCKER_PASSWORD

    - name: Read Secrets for Prime Build
      uses: rancher-eio/read-vault-secrets@main
      if: ${{ inputs.prime_build == 'true' }}
      with:
        secrets: |
          secret/data/github/repo/${{ github.repository }}/rancher-prime-registry/credentials registry | DOCKER_REGISTRY;
          secret/data/github/repo/${{ github.repository }}/rancher-prime-registry/credentials username | DOCKER_USERNAME;
          secret/data/github/repo/${{ github.repository }}/rancher-prime-registry/credentials password | DOCKER_PASSWORD

    - name: Login to Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.DOCKER_REGISTRY }}
        username: ${{ env.DOCKER_USERNAME }}
        password: ${{ env.DOCKER_PASSWORD }}
